version: '3.8'

services:
  #server: 
    #build: "redis"
    #ports:
     # - "3000:3000"
    #depends_on:
    #- DB
    #links:
     # - DB
    #image:
     # chokhonelidze/redisserver:latest
    
  DB:
    image: redis
    restart: always
    container_name: redisDB
    ports:
      - "6379:6379"
      